import StyledComponentsRegistry from "@/lib/AntdRegistry";
import type { Metadata } from "next";
// import { GlobalContextProvides } from "./Context/store";
export const metadata: Metadata = {
	title: "namaz Tracker",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<StyledComponentsRegistry>
					{/* <GlobalContextProvides> */}
					{children}
					{/* </GlobalContextProvides> */}
				</StyledComponentsRegistry>
			</body>
		</html>
	);
}
